language: java
notifications:
  slack:
    secure: nw8QzyjxrioYfxzy9+3JHYTqrpwk/I/MIufqVfzOFDuJ9wfAu3kNGFPgwZV4ka+Akr8EHMgtdJJlmb5azc1fW7qirk9UrkgwJaS0UK1CnrL/8EwOJb4dIfoCR9VI+H99GbXdjQfZHlmUetijQHN7MdPKJds7PSri5J+WNWDQJDM=
deploy:
  provider: releases
  api_key:
    secure: sS7rV82K7MLIBF2mhwF0rMDJD/dEnqXLBVfkkA0U980TJ6ZGdaGRW4ESRNLoUcHCPtX6Vt/QStoohWPw99O1e8MA+qiZxmQK73PlLJCgAwI/HpFAR2KqU7BuB1o9Nhgr2ZCVf3PzjPoCXi8wVahEuSoKmm4vnDl32tpj9vgLMeY=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    tags: true
    repo: xebialabs-community/xl-metrics-plugin
