language: java
notifications:
  hipchat:
    rooms:
      secure: piRsdIga9kPUSVT49zzrGS2MTF7D508A0W141eJf0BSbkmJcBzTD9c5+BiBcoZBkx9w3Nj0fqfaPIV1EVo5azykAa7JcMxiRjLoxfkOzn2+YFaJnbIPNFrZPcda9NcZeyaOxMbjs8wCMLy3uIh65XagBVUbiIOGNnt4wxFkrTRY=
deploy:
  provider: releases
  api_key:
    secure: sS7rV82K7MLIBF2mhwF0rMDJD/dEnqXLBVfkkA0U980TJ6ZGdaGRW4ESRNLoUcHCPtX6Vt/QStoohWPw99O1e8MA+qiZxmQK73PlLJCgAwI/HpFAR2KqU7BuB1o9Nhgr2ZCVf3PzjPoCXi8wVahEuSoKmm4vnDl32tpj9vgLMeY=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    tags: true
    repo: xebialabs-community/xl-metrics-plugin
